import React, { createContext, useContext, useState, useEffect } from "react";

const ThemeContext = createContext();

export const themes = {
  light: {
    name: "Light",
    emoji: "☀️",
    description: "Clean and bright",
    vars: {
      "--bg-primary": "#f9fafb",
      "--bg-secondary": "#ffffff",
      "--bg-tertiary": "#f3f4f6",
      "--bg-hover": "#e5e7eb",
      "--text-primary": "#111827",
      "--text-secondary": "#374151",
      "--text-muted": "#6b7280",
      "--text-inverse": "#ffffff",
      "--border-color": "#e5e7eb",
      "--border-focus": "#4f46e5",
      "--brand-primary": "#4f46e5",
      "--brand-primary-hover": "#4338ca",
      "--accent-primary": "#4f46e5",
      "--accent-primary-hover": "#4338ca",
      "--accent-secondary": "#059669",
      "--accent-secondary-hover": "#047857",
      "--accent-danger": "#ef4444",
      "--accent-danger-hover": "#dc2626",
      "--accent-warning": "#f59e0b",
      "--accent-amber": "#d97706",
      "--accent-purple": "#8b5cf6",
      "--accent-purple-hover": "#7c3aed",
      "--card-shadow": "0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px 0 rgba(0,0,0,0.06)",
      "--card-shadow-hover": "0 4px 16px rgba(0,0,0,0.12)",
      "--modal-bg": "rgba(0,0,0,0.5)",
      "--input-bg": "#ffffff",
      "--tag-bg": "#ede9fe",
      "--tag-color": "#5b21b6",
      "--warning-bg": "#fef3c7",
      "--warning-text": "#92400e",
      "--warning-border": "#fbbf24",
      "--error-bg": "#fee2e2",
      "--error-text": "#991b1b",
      "--error-border": "#fca5a5",
      "--success-bg": "#d1fae5",
      "--success-text": "#065f46",
      "--info-bg": "#eff6ff",
      "--info-text": "#1e40af",
      "--info-border": "#bfdbfe",
      "--nav-bg": "#f0f9ff",
      "--nav-border": "#bae6fd",
      "--gradient-primary": "linear-gradient(135deg, #6366f1, #8b5cf6)",
      "--gradient-hero": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      "--scrollbar-track": "#f1f1f1",
      "--scrollbar-thumb": "#c1c1c1",
    },
  },
  dark: {
    name: "Dark",
    emoji: "🌙",
    description: "Easy on the eyes",
    vars: {
      "--bg-primary": "#0f172a",
      "--bg-secondary": "#1e293b",
      "--bg-tertiary": "#334155",
      "--bg-hover": "#475569",
      "--text-primary": "#f1f5f9",
      "--text-secondary": "#cbd5e1",
      "--text-muted": "#94a3b8",
      "--text-inverse": "#0f172a",
      "--border-color": "#334155",
      "--border-focus": "#818cf8",
      "--brand-primary": "#818cf8",
      "--brand-primary-hover": "#6366f1",
      "--accent-primary": "#818cf8",
      "--accent-primary-hover": "#6366f1",
      "--accent-secondary": "#34d399",
      "--accent-secondary-hover": "#10b981",
      "--accent-danger": "#f87171",
      "--accent-danger-hover": "#ef4444",
      "--accent-warning": "#fbbf24",
      "--accent-amber": "#f59e0b",
      "--accent-purple": "#a78bfa",
      "--accent-purple-hover": "#8b5cf6",
      "--card-shadow": "0 1px 3px 0 rgba(0,0,0,0.4), 0 1px 2px 0 rgba(0,0,0,0.3)",
      "--card-shadow-hover": "0 4px 16px rgba(0,0,0,0.5)",
      "--modal-bg": "rgba(0,0,0,0.75)",
      "--input-bg": "#1e293b",
      "--tag-bg": "#312e81",
      "--tag-color": "#c4b5fd",
      "--warning-bg": "#422006",
      "--warning-text": "#fde68a",
      "--warning-border": "#92400e",
      "--error-bg": "#450a0a",
      "--error-text": "#fca5a5",
      "--error-border": "#991b1b",
      "--success-bg": "#064e3b",
      "--success-text": "#6ee7b7",
      "--info-bg": "#1e3a5f",
      "--info-text": "#93c5fd",
      "--info-border": "#1d4ed8",
      "--nav-bg": "#1e293b",
      "--nav-border": "#334155",
      "--gradient-primary": "linear-gradient(135deg, #4f46e5, #7c3aed)",
      "--gradient-hero": "linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)",
      "--scrollbar-track": "#1e293b",
      "--scrollbar-thumb": "#475569",
    },
  },
  ocean: {
    name: "Ocean",
    emoji: "🌊",
    description: "Cool & refreshing",
    vars: {
      "--bg-primary": "#e0f2fe",
      "--bg-secondary": "#ffffff",
      "--bg-tertiary": "#bae6fd",
      "--bg-hover": "#7dd3fc",
      "--text-primary": "#0c4a6e",
      "--text-secondary": "#075985",
      "--text-muted": "#0369a1",
      "--text-inverse": "#ffffff",
      "--border-color": "#7dd3fc",
      "--border-focus": "#0284c7",
      "--brand-primary": "#0284c7",
      "--brand-primary-hover": "#0369a1",
      "--accent-primary": "#0284c7",
      "--accent-primary-hover": "#0369a1",
      "--accent-secondary": "#059669",
      "--accent-secondary-hover": "#047857",
      "--accent-danger": "#e11d48",
      "--accent-danger-hover": "#be123c",
      "--accent-warning": "#d97706",
      "--accent-amber": "#b45309",
      "--accent-purple": "#7c3aed",
      "--accent-purple-hover": "#6d28d9",
      "--card-shadow": "0 1px 3px 0 rgba(3,105,161,0.2), 0 1px 2px 0 rgba(3,105,161,0.1)",
      "--card-shadow-hover": "0 4px 16px rgba(3,105,161,0.25)",
      "--modal-bg": "rgba(7,89,133,0.5)",
      "--input-bg": "#ffffff",
      "--tag-bg": "#dbeafe",
      "--tag-color": "#1d4ed8",
      "--warning-bg": "#fef3c7",
      "--warning-text": "#92400e",
      "--warning-border": "#fbbf24",
      "--error-bg": "#ffe4e6",
      "--error-text": "#9f1239",
      "--error-border": "#fda4af",
      "--success-bg": "#dcfce7",
      "--success-text": "#166534",
      "--info-bg": "#dbeafe",
      "--info-text": "#1e40af",
      "--info-border": "#93c5fd",
      "--nav-bg": "#0284c7",
      "--nav-border": "#0369a1",
      "--gradient-primary": "linear-gradient(135deg, #0284c7, #0ea5e9)",
      "--gradient-hero": "linear-gradient(135deg, #0369a1 0%, #0284c7 100%)",
      "--scrollbar-track": "#bae6fd",
      "--scrollbar-thumb": "#0284c7",
    },
  },
  sunset: {
    name: "Sunset",
    emoji: "🌅",
    description: "Warm & energetic",
    vars: {
      "--bg-primary": "#fff7ed",
      "--bg-secondary": "#ffffff",
      "--bg-tertiary": "#ffedd5",
      "--bg-hover": "#fed7aa",
      "--text-primary": "#431407",
      "--text-secondary": "#7c2d12",
      "--text-muted": "#9a3412",
      "--text-inverse": "#ffffff",
      "--border-color": "#fed7aa",
      "--border-focus": "#ea580c",
      "--brand-primary": "#ea580c",
      "--brand-primary-hover": "#c2410c",
      "--accent-primary": "#ea580c",
      "--accent-primary-hover": "#c2410c",
      "--accent-secondary": "#16a34a",
      "--accent-secondary-hover": "#15803d",
      "--accent-danger": "#dc2626",
      "--accent-danger-hover": "#b91c1c",
      "--accent-warning": "#d97706",
      "--accent-amber": "#b45309",
      "--accent-purple": "#9333ea",
      "--accent-purple-hover": "#7e22ce",
      "--card-shadow": "0 1px 3px 0 rgba(234,88,12,0.15), 0 1px 2px 0 rgba(234,88,12,0.08)",
      "--card-shadow-hover": "0 4px 16px rgba(234,88,12,0.2)",
      "--modal-bg": "rgba(124,45,18,0.5)",
      "--input-bg": "#ffffff",
      "--tag-bg": "#ffedd5",
      "--tag-color": "#c2410c",
      "--warning-bg": "#fef9c3",
      "--warning-text": "#854d0e",
      "--warning-border": "#fde047",
      "--error-bg": "#fee2e2",
      "--error-text": "#991b1b",
      "--error-border": "#fca5a5",
      "--success-bg": "#dcfce7",
      "--success-text": "#166534",
      "--info-bg": "#eff6ff",
      "--info-text": "#1e40af",
      "--info-border": "#bfdbfe",
      "--nav-bg": "#ea580c",
      "--nav-border": "#c2410c",
      "--gradient-primary": "linear-gradient(135deg, #ea580c, #f59e0b)",
      "--gradient-hero": "linear-gradient(135deg, #c2410c 0%, #ea580c 100%)",
      "--scrollbar-track": "#ffedd5",
      "--scrollbar-thumb": "#ea580c",
    },
  },
  forest: {
    name: "Forest",
    emoji: "🌿",
    description: "Natural & calming",
    vars: {
      "--bg-primary": "#f0fdf4",
      "--bg-secondary": "#ffffff",
      "--bg-tertiary": "#dcfce7",
      "--bg-hover": "#bbf7d0",
      "--text-primary": "#052e16",
      "--text-secondary": "#14532d",
      "--text-muted": "#166534",
      "--text-inverse": "#ffffff",
      "--border-color": "#bbf7d0",
      "--border-focus": "#16a34a",
      "--brand-primary": "#16a34a",
      "--brand-primary-hover": "#15803d",
      "--accent-primary": "#16a34a",
      "--accent-primary-hover": "#15803d",
      "--accent-secondary": "#0284c7",
      "--accent-secondary-hover": "#0369a1",
      "--accent-danger": "#e11d48",
      "--accent-danger-hover": "#be123c",
      "--accent-warning": "#d97706",
      "--accent-amber": "#b45309",
      "--accent-purple": "#9333ea",
      "--accent-purple-hover": "#7e22ce",
      "--card-shadow": "0 1px 3px 0 rgba(22,163,74,0.15), 0 1px 2px 0 rgba(22,163,74,0.08)",
      "--card-shadow-hover": "0 4px 16px rgba(22,163,74,0.2)",
      "--modal-bg": "rgba(5,46,22,0.5)",
      "--input-bg": "#ffffff",
      "--tag-bg": "#dcfce7",
      "--tag-color": "#15803d",
      "--warning-bg": "#fef3c7",
      "--warning-text": "#92400e",
      "--warning-border": "#fbbf24",
      "--error-bg": "#fee8ec",
      "--error-text": "#9f1239",
      "--error-border": "#fda4af",
      "--success-bg": "#dcfce7",
      "--success-text": "#166534",
      "--info-bg": "#dbeafe",
      "--info-text": "#1e40af",
      "--info-border": "#93c5fd",
      "--nav-bg": "#16a34a",
      "--nav-border": "#15803d",
      "--gradient-primary": "linear-gradient(135deg, #16a34a, #0d9488)",
      "--gradient-hero": "linear-gradient(135deg, #15803d 0%, #16a34a 100%)",
      "--scrollbar-track": "#dcfce7",
      "--scrollbar-thumb": "#16a34a",
    },
  },
};

export const ThemeProvider = ({ children }) => {
  const [themeName, setThemeName] = useState(
    () => localStorage.getItem("app-theme") || "light"
  );

  const theme = themes[themeName] || themes.light;

  useEffect(() => {
    const root = document.documentElement;
    Object.entries(theme.vars).forEach(([key, value]) => {
      root.style.setProperty(key, value);
    });
    root.setAttribute("data-theme", themeName);
    localStorage.setItem("app-theme", themeName);
  }, [themeName, theme]);

  const changeTheme = (name) => {
    if (themes[name]) {
      setThemeName(name);
    }
  };

  return (
    <ThemeContext.Provider value={{ themeName, theme, changeTheme, themes }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const ctx = useContext(ThemeContext);
  if (!ctx) throw new Error("useTheme must be used within ThemeProvider");
  return ctx;
};

export default ThemeContext;
